# kafka
kafka.enable: false
spring.kafka:
  bootstrap-servers: localhost:9092
  producer:
    acks: -1
    retries: 100
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: msg-center
    enable-auto-commit: true
    # 自动提交offset的时间间隔
    auto-commit-interval: PT0.5S
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    auto-offset-reset: earliest
xxx:
  group: xxx-msg-center
  topic: xxx-msg-center
ws:
  group: ws-msg-center
  topic: ws-msg-center
